# Generated by Django 4.2.6 on 2023-10-28 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('requirements', models.CharField(max_length=200)),
                ('processing_time', models.CharField(max_length=50)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='VisaApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_proof_type', models.CharField(choices=[('dl', 'Driving License'), ('passport', 'Passport'), ('adhar', 'Adhar Card')], max_length=10)),
                ('address_proof', models.FileField(upload_to='files/')),
                ('id_proof_type', models.CharField(choices=[('dl', 'Driving License'), ('passport', 'Passport'), ('adhar', 'Adhar Card')], max_length=50)),
                ('id_proof', models.FileField(upload_to='files/')),
                ('phone', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visa_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.visaservices')),
            ],
        ),
    ]
